# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_panel.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 761, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tabMain = QtWidgets.QWidget()
        self.tabMain.setObjectName("tabMain")
        self.formLayoutWidget = QtWidgets.QWidget(self.tabMain)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 501, 451))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushFaceInput = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushFaceInput.setObjectName("pushFaceInput")
        self.gridLayout.addWidget(self.pushFaceInput, 6, 0, 1, 1)
        self.labelObject_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelObject_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelObject_2.setObjectName("labelObject_2")
        self.gridLayout.addWidget(self.labelObject_2, 6, 1, 1, 1)
        self.labelHead = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelHead.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelHead.setObjectName("labelHead")
        self.gridLayout.addWidget(self.labelHead, 2, 1, 1, 1)
        self.pushArm = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushArm.setObjectName("pushArm")
        self.gridLayout.addWidget(self.pushArm, 3, 0, 1, 1)
        self.labelArm = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelArm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelArm.setObjectName("labelArm")
        self.gridLayout.addWidget(self.labelArm, 3, 1, 1, 1)
        self.pushObject = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushObject.setObjectName("pushObject")
        self.gridLayout.addWidget(self.pushObject, 5, 0, 1, 1)
        self.labelObject = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelObject.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelObject.setObjectName("labelObject")
        self.gridLayout.addWidget(self.labelObject, 5, 1, 1, 1)
        self.pushHead = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushHead.setObjectName("pushHead")
        self.gridLayout.addWidget(self.pushHead, 2, 0, 1, 1)
        self.labelFaceOutput = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelFaceOutput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelFaceOutput.setObjectName("labelFaceOutput")
        self.gridLayout.addWidget(self.labelFaceOutput, 4, 1, 1, 1)
        self.pushFaceOutput = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushFaceOutput.setObjectName("pushFaceOutput")
        self.gridLayout.addWidget(self.pushFaceOutput, 4, 0, 1, 1)
        self.pushLeap = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushLeap.setObjectName("pushLeap")
        self.gridLayout.addWidget(self.pushLeap, 7, 0, 1, 1)
        self.labelLeap = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelLeap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelLeap.setObjectName("labelLeap")
        self.gridLayout.addWidget(self.labelLeap, 7, 1, 1, 1)
        self.tabWidget.addTab(self.tabMain, "")
        self.tabHead = QtWidgets.QWidget()
        self.tabHead.setObjectName("tabHead")
        self.widgetHead = QtWidgets.QWidget(self.tabHead)
        self.widgetHead.setGeometry(QtCore.QRect(10, 10, 731, 501))
        self.widgetHead.setObjectName("widgetHead")
        self.tabWidget.addTab(self.tabHead, "")
        self.tabArm = QtWidgets.QWidget()
        self.tabArm.setObjectName("tabArm")
        self.tabWidget.addTab(self.tabArm, "")
        self.tabFaceOutput = QtWidgets.QWidget()
        self.tabFaceOutput.setObjectName("tabFaceOutput")
        self.tabWidget.addTab(self.tabFaceOutput, "")
        self.tabObject = QtWidgets.QWidget()
        self.tabObject.setObjectName("tabObject")
        self.tabWidget.addTab(self.tabObject, "")
        self.tabFaceInput = QtWidgets.QWidget()
        self.tabFaceInput.setObjectName("tabFaceInput")
        self.tabWidget.addTab(self.tabFaceInput, "")
        self.tabLeap = QtWidgets.QWidget()
        self.tabLeap.setObjectName("tabLeap")
        self.tabWidget.addTab(self.tabLeap, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CEMIRA - Control Panel"))
        self.pushFaceInput.setText(_translate("MainWindow", "OFF"))
        self.labelObject_2.setText(_translate("MainWindow", "Launch Face Feature Rec. Nodes"))
        self.labelHead.setText(_translate("MainWindow", "Launch Head Control Nodes"))
        self.pushArm.setText(_translate("MainWindow", "OFF"))
        self.labelArm.setText(_translate("MainWindow", "Launch Arm Control Nodes"))
        self.pushObject.setText(_translate("MainWindow", "OFF"))
        self.labelObject.setText(_translate("MainWindow", "Launch Object Recognition Nodes"))
        self.pushHead.setText(_translate("MainWindow", "OFF"))
        self.labelFaceOutput.setText(_translate("MainWindow", "Launch Face & Speech Output Nodes"))
        self.pushFaceOutput.setText(_translate("MainWindow", "OFF"))
        self.pushLeap.setText(_translate("MainWindow", "OFF"))
        self.labelLeap.setText(_translate("MainWindow", "Launch Leap Gesture Rec. Nodes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("MainWindow", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHead), _translate("MainWindow", "Head"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabArm), _translate("MainWindow", "Arm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFaceOutput), _translate("MainWindow", "Face Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabObject), _translate("MainWindow", "Object Rec."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFaceInput), _translate("MainWindow", "Face Input"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLeap), _translate("MainWindow", "Leap"))

